# Generated by Django 3.0.7 on 2021-11-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_stuff', '0002_auto_20211102_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
