# Generated by Django 3.0.7 on 2021-11-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_stuff', '0004_auto_20211102_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(max_length=255),
        ),
    ]
